site_name: OpenMod Documentation
coypright: 'The OpenMod Documentation is licensed under the terms of the Creative Commons Attribution Share Alike 4.0 International license.'
site_description: 'OpenMod .NET Plugin Framwework Documentation'
docs_dir: 'content'
repo_name: 'openmod/openmod'
site_url: 'https://openmod.github.io/openmod-docs/'
repo_url: 'https://github.com/openmod/openmod'
edit_uri: 'https://github.com/openmod/openmod-docs/edit/master/content/'
pages:
    - Home: index.md
    - User Guide:
        - Installation:
            - Installing OpenMod for Unturned: user-guide/installation/unturned.md
            - Managing Auto Updates: user-guide/installation/auto-updates.md
        - Migration:
            - Migrating from RocketMod: user-guide/migration/rocketmod.md         
        - Plugins: 
            - Installing and managing plugins: user-guide/plugins/plugin-management.md
        - Configurations: user-guide/configurations.md
        - Localization: user-guide/localization.md
        - Permissions: user-guide/permissions.md
        - Logging: user-guide/logging.md
    - Development Guide:
        - Making your first plugin: development-guide/making-your-first-plugin.md
        - Commands: development-guide/commands.md
        - Configuration: development-guide/configuration.md
        - Localization: development-guide/localization.md
        - Scheduling: development-guide/scheduling.md
        - Services: development-guide/services.md
        - Logging: development-guide/logging.md
        - Permissions: development-guide/permissions.md
        - Data Store: development-guide/datastore.md # todo
        - Events:
            - Events and event listeners: development-guide/events/events.md # todo
            - Built-in events: development-guide/events/builtin-events.md # todo
            - Game events: development-guide/events/game-events.md # todo
        - Publishing to nuget.org: development-guide/publishing-to-nuget.md
plugins:
  - search
  - autoreflinks
theme:
  name: 'material'
  palette:
    primary: 'cyan'
    accent: 'light blue'
  language: 'en'
  feature:
    tabs: true  
markdown_extensions:
  - admonition
  - meta
  - sane_lists
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  